INSERT INTO
posts(category, title, organization, positions_available, description, thumbnail_photo_url, street, city, province, post_code, date_posted, start_date, requirements, additional_info, active, user_id)
VALUES
    (
        'Environment', 'Earth Day Clean-ups Volunteer', 'Earthday', 20, 'On Earth Day join hundreds of high school students to clean Toronto together! Choose a location that works best for you and sign-up with your friends.On Earth Day join hundreds of high school students to clean Toronto together! Choose a location that works best for you and sign-up with your friends.', 'https://images.pexels.com/photos/346885/pexels-photo-346885.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260', '1 Yonge Street', 'Toronto', 'Ontario', 'M2D3K4', '2020-11-20', '2020-12-25', 'No previous experience necessary', 'N/A', true, 1
    ),
    (
        'Education', 'Volunteer Mentor', 'Education of Canada ', 5, 'Be a leader in connecting students and creating our campus culture.Peer mentors act as advisors and offer support to incoming students. Peer mentors will offer support by providing access and referrals to appropriate resources regarding academic concerns or resources within Student Success and Engagement as needed. Peer Mentors will aid in the creation of a Faculty - Student connection, both inside the classroom and outside.', 'https://images.pexels.com/photos/935949/pexels-photo-935949.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '1265 Military Trail', 'Scarborough', 'Ontario', 'M1C1A4', '2020-11-2', '2021-01-09', 'Background check', 'N/A', true, 2
    ),
    (
        'Community', 'Crew Leader', 'Home 4U Ontario', 4, 'Crew Leaders are an integral part of the Habitat mission. We look for volunteers who will be able to motivate, teach and lead a group of (potentially) inexperienced volunteers in a construction task for the day. If you have a combination of construction experience, team leadership skills and can contribute a full day’s work, this position may be for you.', 'https://images.pexels.com/photos/2098624/pexels-photo-2098624.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '755 Lawrence Ave E', 'North York', 'Ontario', 'M3C1P2', '2020-09-26', '2021-06-25', 'Background check', 'N/A', true, 3
    ),
    (
        'Animals', 'Wildlife Videographer and Content Creator', 'Wildlife Society', 2, 'Wildlife Society is pleased to be hiring a Wildlife Videographer and Content Creator Intern. We are a small organization that looking for someone who is passionate about documenting wildlife to share with the world.', 'https://images.pexels.com/photos/374719/pexels-photo-374719.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', '220 Cranston Park Ave', 'Maple', 'Ontario', 'L6A2M4', '2020-11-19', '2021-01-20', 'N/A', 'N/A', true, 4
    ),
    (
        'Health', 'Patient Companion', 'Apple Healthcare', 10, 'Be a friend to a patient, resident or client who may not have visitors on a regular basis by escorting them to various activities, taking them for walks or simply having a friendly chat. This position can be added to Meal Assistance. Shift times can accommodate your schedule.', 'https://images.pexels.com/photos/339619/pexels-photo-339619.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '3276 St Clair Ave E', 'Scarborough', 'Ontario', 'M1L1W1', '2020-09-20', '2020-12-25', 'Background check', 'N/A', true, 5
    ),
    (
        'Sports', 'Youth Ambassador', 'Jays Care Foundation', 2, 'Used intentionally, baseball has the power to create lasting social change for children and youth. That is why we help kids get involved in the game, build safe spaces in which they can play and support organizations dedicated to improving the lives of all Canadian kids.', 'https://images.pexels.com/photos/139762/pexels-photo-139762.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '1 Blue Jays Way', 'Toronto', 'Ontario', 'M5V1J1', '2020-09-20', '2020-12-10', 'Background check', 'N/A', true, 1
    ),
    -- (
    --     'Health', 'Inpatient Support', 'University Health Network', 2, '​​​​​​​​​​​​​​​​​​​​​​​​​​Provide activities for patients – examples include providing reading material, playing cards, board games, puzzles, talking, reading to patients, writing letters, arts and crafts. Communicate between patients/families and nursing/health professions staff – inform nursing/health professions staff about patients and visitors who wish to talk with medical staff. Keep staff informed of any questions or concerns raised.', 'https://images.pexels.com/photos/4386466/pexels-photo-4386466.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '2867 Ellesmere Road', 'Scarborough', 'Ontario', 'M1E4B9', '2020-11-27', '2021-02-20', 'Background check', 'N/A', true, 2
    -- ),
    (
        'Health', 'General Patient and Family Support', 'Rouge Valley Hospital', 3, '​​​​​​​​​​​​​​​​​​​​​​​​​​Assist with way-finding, direct and escort patients and other clients (e.g., family members, visitors) to different areas in the hospital.
        Provide information pertaining to a patient’s visit to the hospital Greet and welcome visitors. Examples – Navigator, Information Desk Waiting Room Support, Critical Care Units, Emergency Department. ', 'https://images.pexels.com/photos/127873/pexels-photo-127873.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '381 Church Street', 'Markham', 'Ontario', 'L3P7P3', '2020-11-11', '2021-03-01', 'Background check', 'N/A', true, 2
    ),
    (
        'Community', 'Community Engagement Coordinator', 'LTJ Corporate Development Solutions', 1, '​​​​​​​​​​​​​​​​​​​​​​​​​​We are seeking a volunteer Community Engagement Coordinator for our Toronto-based client. Our client is a non-profit organization founded in 2015, dedicated to helping young women and girls reach their fullest potential through its three pillars: Independence, Leadership, and Confidence. Reporting to the Community Engagement Manager, the Community Engagement Coordinator will develop and cultivate relationships with diverse community partners, including but not limited to schools, youth groups, faith-based groups, and shelters. Additionally, the Community Engagement Coordinator will manage regional and local volunteer teams and all aspects of the client’s community service programs.', 'https://images.pexels.com/photos/53958/team-motivation-teamwork-together-53958.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '120 Berner Trail', 'Scarborough', 'Ontario', 'M1B1B5', '2020-11-15', '2021-02-01', 'Background check', 'N/A', true, 2
    ),
    (
        'Disaster', 'Emergency Response Team (ERT) Responder', 'Blue Cross', 1, '​​​​​​​​​​​​​​​​​​​There is a current – and critical – need for volunteers to join our Emergency Management Team today. Disasters now endanger more Canadians and cause more devastation than ever before. Whenever they do, the Canadian Red Cross is prepared to help and ready to respond. And you can be too. We train and guide you on how to safely provide vital services to people affected by an emergency or a disaster – either large or small. As well, you will learn how to provide practical and emotional support to people who have suddenly found themselves without a home and have turned to the Canadian Red Cross for help.', 'https://images.pexels.com/photos/98014/pexels-photo-98014.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '1873 Bloor St W', 'Toronto', 'Ontario', 'M6R2Z3', '2020-11-01', '2021-04-01', 'Background check', 'N/A', true, 2
    ),
    (
        'Youth', 'Kids Coach', 'Future Goals for Kids', 1, 'You will have the opportunity to coach a Kid as they set out to accomplish a community-oriented goal. Following a structured curriculum in one to one coaching, you will help a kid learn how to reach higher, try new things and discover a new level of self confidence that will make a lasting difference in their lives. Our adult coaches have fun too, while they develop coaching skills and connect with other volunteers in the program.', 'https://images.pexels.com/photos/264337/pexels-photo-264337.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '115 Cumberland Street', 'Toronto', 'Ontario', 'M5S2W7', '2020-11-01', '2021-02-01', 'Background check', 'N/A', true, 2
    ),
    (
        'Environment', 'Tree Planter', 'Trees for ALL', 15, 'There are few things in life more satisfying rewarding, enriching, fulfilling, and fun than volunteering for a worthwhile cause. 10,000 Trees is precisely such a cause, and since our inception in 1989, countless dedicated volunteers have happily planned, prepared, and planted more than 300,000 trees, shrubs, and wildflowers, in the process restoring hundreds of acres of deteriorated watersheds and transforming them into vibrant habitats teeming with life of all forms.', 'https://images.pexels.com/photos/1072824/pexels-photo-1072824.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '23 Roncesvalles Ave', 'Toronto', 'Ontario', 'm6r2k2', '2020-11-30', '2021-05-01', 'Background check', 'N/A', true, 2
    ),
    (
        'Arts', 'Arts Instructor', 'Creative Community', 10, 'Cupcake ipsum dolor. Sit amet marshmallow topping cheesecake muffin. Halvah croissant candy canes bonbon candy. Apple pie jelly beans topping carrot cake danish tart cake cheesecake. Muffin danish chocolate soufflé pastry icing bonbon oat cake. Powder cake jujubes oat cake. Lemon drops tootsie roll marshmallow halvah carrot cake.', 'https://images.pexels.com/photos/3298835/pexels-photo-3298835.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '23 Roncesvalles Ave', 'Toronto', 'Ontario', 'm6r2k2', '2020-11-05', '2021-05-01', 'Background check', 'N/A', true, 5
    ),
    (
        'Disaster', 'Firefighter', 'Disaster HELPS ALL', 5, 'Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium.', 'https://images.pexels.com/photos/70573/fireman-firefighter-rubble-9-11-70573.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '23 Roncesvalles Ave', 'Toronto', 'Ontario', 'm6r2k2', '2020-10-05', '2021-05-01', 'Background check', 'N/A', true, 1
    ),
    (
        'Seniors', 'Seniors Aide', 'Royal Ontario Society', 3, 'Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before. Many say exploration is part of our destiny, but it’s actually our duty to future generations and their quest to ensure the survival of the human species.', 'https://images.pexels.com/photos/1307391/pexels-photo-1307391.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '23 Roncesvalles Ave', 'Toronto', 'Ontario', 'm6r2k2', '2020-08-05', '2021-05-01', 'Background check', 'N/A', true, 3
    ),
    (
        'Religious', 'Library Assistant', 'Religion 4 You', 6, 'TWell, the way they make shows is, they make one show. That show is called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they are going to make more shows. Some pilots get picked and become television programs. Some do not, become nothing. She starred in one of the ones that became nothing.', 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '23 Roncesvalles Ave', 'Toronto', 'Ontario', 'm6r2k2', '2020-10-20', '2021-02-01', 'Background check', 'N/A', true, 5
    ),
    (
        'Youth', 'Program Manager', 'You And Me Build The World', 1, 'Sportacus andrew weatherall goose Refined gentlemen super mario des lynam alpha trion zap rowsdower, omar sharif old man in pub burt reynolds alpha trion sportacus villain Refined gentlemen zap rowsdower funny walk super mario frightfully nice andrew weatherall des lynam goose. Semi beard cream bun disaster alpha trion? Refined gentlemen zap rowsdower funny walk super mario frightfully nice andrew weatherall des lynam goose. Semi beard cream bun disaster alpha trion?', 'https://images.pexels.com/photos/939702/pexels-photo-939702.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '23 Roncesvalles Ave', 'Toronto', 'Ontario', 'm6r2k2', '2020-11-05', '2021-01-01', 'Background check', 'N/A', true, 3
    ),
    (
        'Animals', 'Adoption Volunteer', 'Loving Animals', 1, 'The first mate and his Skipper too will do their very best to make the others comfortable in their tropic island nest. Michael Knight a young loner on a crusade to champion the cause of the innocent. The helpless. The powerless in a world of criminals who operate above the law. Here he comes Here comes Speed Racer. He is a demon on wheels.', 'https://images.pexels.com/photos/5575057/pexels-photo-5575057.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', '23 Roncesvalles Ave', 'Toronto', 'Ontario', 'M6R2K2', '2020-11-29', '2021-01-01', 'Background check', 'N/A', true, 3
    );;



    